## NumPy Array

In [3]:
import numpy as np
arr1 = np.array([2 , 4 , 6 , 8 , 10])
arr2 = np.array([[3 , 6 , 9] , [12 , 15 , 18]])
print("1D - Array:",arr1)
print("2D - Array:\n",arr2)

1D - Array: [ 2  4  6  8 10]
2D - Array:
 [[ 3  6  9]
 [12 15 18]]


### Array only with ZEROS

In [5]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### Array only with ONES

In [6]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### Array filled with Specified nos

In [7]:
np.full((3 , 3),4)

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

### Identity Matrix

In [10]:
np.eye((2))

array([[1., 0.],
       [0., 1.]])

### Range of Array

In [14]:
np.arange(1 , 10, 2)

array([1, 3, 5, 7, 9])

### Evenly Spaced Array

In [16]:
np.linspace(0 , 1 , 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

- <b>NumPy offers powerful shortcutts to create arrays without loops</b>

# Properties of NumPy Array

In [18]:
arr = np.array([2 , 4 , 6 , 8 , 10])
print("The shape of the arr is:",arr.shape)
print("The dimension of the array is:",arr.ndim)
print("The size of the Array is:",arr.size)
print("The DataType of the array is:",arr.dtype)

The shape of the arr is: (5,)
The dimension of the array is: 1
The size of the Array is: 5
The DataType of the array is: int64


- <b> Numpy are strongly typed i.e all elements have the same data type.</b>

## Changing DType

In [19]:
arr = np.array([1, 2, 3], dtype=np.float32)  # Explicit type
print(arr.dtype)  # float32

arr_int = arr.astype(np.int32)  # Convert float to int
print(arr_int)  # [1 2 3]

float32
[1 2 3]


## Reshaping and Flattening Array

In [20]:
arr = np.array([[2 , 4 , 8] , [8 , 10 , 12]])
arr.shape

(2, 3)

In [21]:
arr.reshape(3,2)

array([[ 2,  4],
       [ 8,  8],
       [10, 12]])

In [22]:
arr.flatten()

array([ 2,  4,  8,  8, 10, 12])