# Indexing and slicing

### Indexing (Same as Python Lists)

In [19]:
arr = np.array([10, 20, 30, 40])
print(arr[0]) 
print(arr[-1])

10
40


### Slicing (Extracting Parts of an Array)

In [20]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[1:4]) # (slice from index 1 to 3)
print(arr[:3]) # (first 3 elements)
print(arr[::2]) #  (every 2nd element)

[20 30 40]
[10 20 30]
[10 30 50]


### Fancy Indexing & Boolean Masking

- Fancy Indexing (Select Multiple Elements)

In [22]:
arr = np.array([10, 20, 30, 40, 50])
idx = [0, 2, 4] 
print(arr[idx]) 

[10 30 50]


- Boolean Masking (Filter Data)

In [25]:
arr = np.array([10, 20, 30, 40, 50])
mask = arr > 25 # Condition: values greater than 25
print(arr[mask])

[30 40 50]
